name: Refresh GitHub Repo Cache

on:
  schedule:
    # daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  refresh:
    name: Refresh cached repo list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Ensure script is executable
        run: chmod +x scripts/refresh-repos.mjs

      - name: Run repo refresh script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: node scripts/refresh-repos.mjs

      - name: Commit and push cache if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .cache/*.json || true
          if git diff --cached --quiet; then
            echo "No cache changes to commit."
          else
            git commit -m "chore: refresh repo cache [ci skip]" || true
            git push
          fi

  build:
    needs: refresh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: .
          node-version: 24
          package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
